parameters:
  - name: jobName
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""

stages:
  - stage: BuildandPackage
    displayName: "Build and Package Artifact"
    jobs:
      - job: ApplicationBuildandPackage
        displayName: ${{ parameters.jobName }}
        steps:
          - task: NodeTool@0
            displayName: "Setup Node.JS Environment"
            inputs:
              versionSource: "spec"
              versionSpec: "16.x"

          - task: Npm@1
            displayName: "npm install"
            inputs:
              command: "install"
              workingDir: ${{ parameters.workingDirectory }}

          - task: Npm@1
            displayName: "npm run build"
            inputs:
              command: "custom"
              workingDir: ${{ parameters.workingDirectory }}
              customCommand: "run build"

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact"
            inputs:
              PathtoPublish: '${{ parameters.workingDirectory }}/build'
              ArtifactName: "todo-ui-build"
              publishLocation: "Container"
