parameters:
  - name: jobName
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""

stages:
  - stage: CodeQualityChecks
    displayName: "Code Quality Check"
    jobs:
      - job: LintingChecks
        displayName: ${{ parameters.jobName }}
        steps:
          - task: Bash@3
            displayName: "Java Script Linting - Biome"
            inputs:
              targetType: "inline"
              script: biome lint .
              workingDirectory: ${{ parameters.workingDirectory }}
