parameters:
  - name: jobName
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""

stages:
  - stage: SoftwareCompositionAnalysis
    displayName: "Software Composition Analysis"
    jobs:
      - job: DependancyVulnerabilitySecurity
        displayName: ${{ parameters.jobName }}
        steps:
          - task: NodeTool@0
            displayName: "Setup Node.JS Environment"
            inputs:
              versionSource: "spec"
              versionSpec: "20.x"
              
          - task: Bash@3
            displayName: "Install Dependencies"
            inputs:
              targettype: "inline"
              script: npm ci
              workingDirectory: ${{ parameters.workingDirectory}}

          - task: Bash@3
            displayName: "RetireJs Scan"
            inputs:
              targetType: "inline"
              script: |
                npm install -g retire
                retire --path .
              workingDirectory: ${{ parameters.workingDirectory}}
            continueOnError: true
