parameters:
  - name: jobName
    type: string
    default: ""

stages:
  - stage: SoftwareCompositionAnalysis
    displayName: 'Software Composition Analysis'
    jobs:
      - job: DependancyVulnerabilitySecurity
        displayName: 'Dependancy Vulnerability Security - Retire.JS'
        steps:

          - task: Bash@3
            displayName: ${{ parameters.jobName }}
            inputs:
              targettype: 'inline'
              script: |
                npm install -g retire
                npm install
                retire --exitwith 1
