parameters:
  - name: sonar-host
    type: string
    default: ""

  - name: sonar-token
    type: string
    default: ""

  - name: sonar-project
    type: string
    default: ""

  - name: working-directory
    type: string
    default: ""

stages:
  - stage: StaticCodeAnalysis
    displayName: 'Static Code Analysis'
    jobs:
      - job: SonarqubeAnalysis
        displayName: 'Static Code Analysis - Sonarqube'
        steps:
          
          - task: Bash@3
            displayName: 'Sonarqube Scan'
            inputs:
              targetType: 'inline'
              script: |
                sonar-scanner \
                -D sonar.host.url=${{ parameters.sonar-host }} \
                -D sonar.token=${{ parameters.sonar-token }} \
                -D sonar.projectKey=${{ partameters.sonar-project }} \
                -Dsonar.qualitygate.wait=true
              workingDirectory: ${{ parameters.working-directory }}