parameters:
  - name: jobName
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""

stages:
  - stage: CodeQualityChecks
    displayName: "Code Quality Check"
    jobs:
      - job: LintingChecks
        displayName: ${{ parameters.jobName }}
        steps:
          - task: NodeTool@0
            displayName: "Setup Node.JS Environment"
            inputs:
              versionSource: "spec"
              versionSpec: "20.x"

          - task: Bash@3
            displayName: "README Linting (Markdownlint)"
            inputs:
              targetType: "inline"
              script: |
                npm install -g markdownlint-cli
                markdownlint "**/*.md" --ignore node_modules
              workingDirectory: ${{ parameters.workingDirectory }}
            continueOnError: true

          - task: Bash@3
            displayName: "Python Linting (Ruff)"
            inputs:
              targetType: "inline"
              script: |
                python3 -m venv .venv
                source .venv/bin/activate

                pip install --upgrade pip
                pip install ruff

                ruff check app.py
              workingDirectory: ${{ parameters.workingDirectory }}

