parameters:
  - name: jobName
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""

stages:
  - stage: SoftwareCompositionAnalysis
    displayName: "Software Composition Analysis"
    jobs:
      - job: DependancyVulnerabilitySecurity
        displayName: ${{ parameters.jobName }}
        steps:
          - task: Bash@3
            displayName: "Bandit Scan"
            inputs:
              targetType: "inline"
              script: |
                python3 -m venv .venv
                source .venv/bin/activate

                pip install --upgrade pip
                pip install bandit

                bandit app.py -lll
              workingDirectory: ${{ parameters.workingDirectory }}

          - task: Bash@3
            displayName: "Pip-Audit Scan"
            inputs:
              targetType: 'inline'
              script: |
                python3 -m venv .venv
                source .venv/bin/activate

                pip install --upgrade pip
                pip install pip-audit

                pip-audit -r requirements.txt --strict
              workingDirectory: ${{ parameters.workingDirectory }}
