parameters:
  - name: jobName
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""

stages:
  - stage: SoftwareCompositionAnalysis
    displayName: "Software Composition Analysis"
    jobs:
      - job: DependancyVulnerabilitySecurity
        displayName: ${{ parameters.jobName }}
        steps:
          - task: UsePythonVersion@3
            displayName: "Setup Python"
            inputs:
              versionSpec: "3.x"
              
          - task: Bash@3
            displayName: "Bandit Scan"
            inputs:
              targetType: "inline"
              script: |
                python3 -m pip install --upgrade pip
                pip install bandit
                bandit app.py -ll
              workingDirectory: ${{ parameters.workingDirectory }}
