parameters:
  - name: jobName
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""

stages:
  - stage: SoftwareCompositionAnalysis
    displayName: 'Software Composition Analysis'
    jobs:
      - job: DependancyVulnerabilitySecurity
        displayName: ${{ parameters.jobName }}
        steps:

          - task: Bash@3
            displayName: 'Trivy Scan'
            inputs:
              targetType: 'inline'
              script: |
                trivy fs . \
                  --severity LOW,MEDIUM,HIGH,CRITICAL
              workingDirectory: ${{ parameters.workingDirectory }}
